import { Candidate } from "@/types";

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "1",
    rank: 1,
    initials: "AR",
    name: "Aditya Rao",
    current_role: "Senior ML Engineer · 5yr",
    experience_years: 5,
    overall_score: 91,
    confidence: 87,
    summary: "Strong PyTorch depth with production deployment experience.",
    signals: [
      { label: "Semantic", value: 94, explanation: "High keyword overlap with JD." },
      { label: "Trajectory", value: 88, explanation: "Consistent promotions to Senior." },
      { label: "Impact", value: 82, explanation: "Led major model rewrites." },
      { label: "Velocity", value: 64, explanation: "Steady learning pace." },
    ],
    skills: ["PyTorch", "MLOps"],
    stage: "Shortlisted",
    green_flags: [
      "Strong PyTorch depth with production deployment experience.",
      "Career arc shows deliberate ML platform specialization.",
      "GitHub signal: 12 repos, 4 with >50 stars.",
    ],
    red_flags: [],
  },
  {
    id: "2",
    rank: 2,
    initials: "SK",
    name: "Sanya Kapoor",
    current_role: "ML Ops Engineer · 4yr",
    experience_years: 4,
    overall_score: 84,
    confidence: 82,
    summary: "Solid infrastructure background.",
    signals: [
      { label: "Semantic", value: 87, explanation: "Matches DevOps needs." },
      { label: "Trajectory", value: 80, explanation: "Good recent growth." },
      { label: "Impact", value: 76, explanation: "Built deployment pipelines." },
      { label: "Velocity", value: 70, explanation: "Learning k8s quickly." },
    ],
    skills: ["Kubernetes", "Terraform"],
    stage: "Interview",
    green_flags: [
      "Kubernetes mastery aligned with infra needs.",
      "Consistent delivery on scalable architectures.",
    ],
    red_flags: [],
  },
  {
    id: "3",
    rank: 3,
    initials: "PM",
    name: "Priya Mehta",
    current_role: "Data Scientist · 3yr",
    experience_years: 3,
    overall_score: 78,
    confidence: 75,
    summary: "Good analytics, needs more engineering.",
    signals: [
      { label: "Semantic", value: 81, explanation: "Matches data needs." },
      { label: "Trajectory", value: 72, explanation: "Standard progression." },
      { label: "Impact", value: 74, explanation: "Delivered analytics dashboards." },
      { label: "Velocity", value: 58, explanation: "Learning curve on DL." },
    ],
    skills: ["TensorFlow", "SQL"],
    stage: "Screening",
    green_flags: [
      "Solid analytical foundation but lighter on deep learning frameworks.",
      "Good trajectory in data pipeline optimization.",
    ],
    red_flags: [],
  },
  {
    id: "4",
    rank: 4,
    initials: "DN",
    name: "Dev Nair",
    current_role: "Backend Engineer · 6yr",
    experience_years: 6,
    overall_score: 72,
    confidence: 90,
    summary: "Backend expert, lacks ML.",
    signals: [
      { label: "Semantic", value: 75, explanation: "Partial match." },
      { label: "Trajectory", value: 68, explanation: "Stable backend role." },
      { label: "Impact", value: 70, explanation: "Built reliable APIs." },
      { label: "Velocity", value: 55, explanation: "No recent ML learning." },
    ],
    skills: ["Go", "Postgres"],
    stage: "Screening",
    green_flags: [
      "Strong backend engineering fundamentals.",
    ],
    red_flags: [
      "Limited direct ML experience, requires onboarding.",
    ],
  },
];
